# Generated by Django 4.0.6 on 2023-02-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_teacher_options_remove_project_finish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='project',
        ),
    ]
