# Generated by Django 4.1.6 on 2023-04-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_teacher_student_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='bob.jpeg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
